config/routes.rb
Rails.application.routes.draw do
  resources :games, only: [:index, :create, :show] do
    resources :players, only: [:create, :update]
  end
  root 'games#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/frame.rb
class Frame < ApplicationRecord
  belongs_to :player
  include FrameBooleanMethods

  def initialize(object)
    super
    self.frame_number = object[:frame_number]
  end

  # Calls set_throw_value with the number of pins knocked down by the bowl
  # Returns the frame referenced by self
  def bowl(pins)
    raise_bowl_errors(pins)
    set_throw_value(pins)
    self
  end

  # Sets the appropriate throw attribute (:first_throw, :second_throw, or :third_throw) to pins
  def set_throw_value(pins)
    if two_throws?
      self.update(third_throw: pins)
    elsif first_throw
      self.update(second_throw: pins)
    else
      self.update(first_throw: pins)
    end
  end

  # Returns the sum of all throws in the current frame (0 for nil)
  def pins_sum
    self.first_throw.to_i + self.second_throw.to_i + self.third_throw.to_i
  end

  # Returns an array of all throws that have been set, in order
  def moves
    [first_throw, second_throw, third_throw].compact
  end

  # Sets the frame's cumulative_score attribute to total_score
  def update_cumulative_score(total_score)
    self.update(cumulative_score: total_score)
  end

  # Updates the score attribute of the frame, if possible
  # If next_frame is nil, strike and spare scores will not be updated
  # If next_next_frame is nil, double strike scores will not be updated
  def update_score(next_frame, next_next_frame)
    moves = Frame.get_next_moves(next_frame, next_next_frame)
    if tenth_frame?
      self.update(score: pins_sum)
    elsif strike? && (moves.length > 1)
      self.update(score: pins_sum + moves[0] + moves[1])
    elsif spare? && (moves.length > 0)
      self.update(score: pins_sum + moves[0])
    elsif !strike? && !spare?
      self.update(score: pins_sum)
    end
    self.score
  end

  def <=>(other_frame)
    self.frame_number <=> other_frame.frame_number
  end

  # Returns an array representation of the frame: 'X' for strikes and '/' for spares
  def to_a
    moves = self.moves

    if strike?
      moves[0] = 'X'
    end

    if spare?
      moves[1] = '/'
    elsif self.second_throw.to_i == 10
      moves[1] = 'X'
    end

    if self.third_throw.to_i == 10
      moves[2] = 'X'
    elsif (self.third_throw && (self.second_throw.to_i + self.third_throw.to_i == 10))
      moves[2] = '/'
    end

    moves
  end

  # Returns an array of all moves in next_frame and next_next_frame
  def self.get_next_moves(next_frame, next_next_frame)
    moves = []
    moves += next_frame.moves if next_frame
    moves += next_next_frame.moves if next_next_frame
    moves
  end

  private

    def raise_bowl_errors(pins)
      if pins > 10
        raise 'Pins limit exceeded!'
      elsif !tenth_frame? && (pins_sum + pins) > 10
        raise 'Pins limit exceeded!'
      elsif complete?
        raise 'Throws already set.'
      end
    end
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :players
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :game
  has_many :frames

  def initialize(object = {})
    super
    self.frame_number = 1
    self.total_score = 0
    self.frames << Frame.new({frame_number: self.frame_number})
  end

  # Bowls for the current frame, and increments the current frame if necessary
  # Returns the player referenced by self
  def bowl(pins)
    raise_bowl_errors
    current_frame.bowl(pins)
    if current_frame.complete?
      update_frame_scores
      increment_frame if !done?
    end
    self
  end

  # Iterates through frames and attempts to score all that haven't yet been scored
  # Calls update_total_score for each newly scored frame
  def update_frame_scores
    sorted_frames = self.frames.sort
    sorted_frames.each_with_index do |frame, index|
      if !frame.score
        frame_score = frame.update_score(sorted_frames[index+1], sorted_frames[index+2])
        update_total_score(frame_score, frame)
      end
    end
  end

  # Updates the total_score attribute by adding frame_score to the previous total
  # Calls Frame#update_cumulative_score for frame
  def update_total_score(frame_score, frame)
    if frame_score
      self.update(total_score: total_score + frame_score)
      frame.update_cumulative_score(self.total_score)
    end
  end

  def current_frame
    self.frames.last
  end

  def increment_frame
    self.update(frame_number: frame_number+1) && self.frames << Frame.new({frame_number: self.frame_number})
  end

  def done?
    current_frame.complete? && self.frames.length == 10
  end

  private

    def raise_bowl_errors
      if done?
        raise "Game over!"
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/frames_controller.rb
class FramesController < ApplicationController
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
    @game = Game.new
  end

  def create
    game = Game.new(game_params)
    respond_to do |format|
      if game.save
        format.html  { redirect_to(games_path) }
        format.js    { render action: :create, locals: {id: game.id} }
      else
        format.html  { render action: :index }
      end
    end
  end

  def show
    @game = Game.find(params[:id])
    @players = @game.players
  end

  private
    def game_params
      params.require(:game).permit(:name)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def create
    game = Game.find(params[:game_id])
    player = game.players.build({name: params[:player][:name]})

    respond_to do |format|
      if game.save
        format.html  { redirect_to(game) }
        format.js    { render action: :create, locals: {id: player.id} }
      else
        format.html  { render action: :show }
      end
    end
  end

  def update
    @game = Game.find(params[:game_id])
    @player = Player.find(params[:id])
    @player.bowl(params[:score].to_i)

    arrays = @player.frames.sort.map{ |frame| frame.to_a }

    respond_to do |format|
      format.html { redirect_to @game }
      format.js   { render action: :update, locals: {player: @player.to_json, frames: @player.frames.sort.to_json, arrays: arrays.to_json} }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frames_helper.rb
module FramesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/games/_player_bowl_form.html.erb
<%= form_tag(game_player_path(game.id, player.id), remote: true, method: "patch") do %>
  <%= label_tag(:score, "Bowl for #{player.name}:") %>
  <%= text_field_tag(:score) %>
  <%= submit_tag("Bowl!") %>
<% end %>

app/views/games/_player_frames.html.erb
<%= render partial: "games/frames/name_frame", locals: {player: player} %>
<%= render partial: "games/frames/completed_frames", locals: {player: player} %>
<%= render partial: "games/frames/empty_frames", locals: {player: player} %>

app/views/games/create.js.erb
$('#games-list').append('<p><%= link_to(params[:game][:name], game_path(id)) %></p>');
$('#game_name').val('');

app/views/games/frames/_completed_frames.html.erb
<% player.frames.sort.each do |frame| %>
  <div class="frame col">
    <p>
      <% frame.to_a.each do |move| %>
        <%= move %>
      <% end %>
    </p>
    <p><%= frame.cumulative_score %></p>
  </div>
<% end %>

app/views/games/frames/_empty_frames.html.erb
<% (10 - player.frames.length).times do %>
  <div class="frame col">
  </div>
<% end %>

app/views/games/frames/_name_frame.html.erb
<div class="frame col">
  <%= player.name %>
</div>

app/views/games/index.html.erb
<div id="games-list">
<% @games.each do |game| %>
  <p><%= link_to(game.name, game) %></p>
<% end %>
</div>

<div class="panel panel-default">
  <h4>Add a New Game</h4>
  <%= form_for @game, remote: true do |f| %>
    <%= f.label :name, "Game Name:" %>
    <%= f.text_field :name %>
    <%= f.submit "New Game" %>
  <% end %>
</div>

app/views/games/show.html.erb
<h3><%= @game.name %></h3>

<div id="bowlers-list">
<% @players.each do |player| %>
  <div class="row" data-id="<%= player.id %>">
    <%= render partial: "player_frames", locals: {player: player} %>
  </div>
<% end %>
</div>

<div class="panel panel-default">
  <h4>Bowl!</h4>
  <div id="bowlers-forms">
  <% @players.each do |player| %>
    <%= render partial: "player_bowl_form", locals: {player: player, game: @game} %>
  <% end %>
  </div>
</div>

<div class="panel panel-default">
  <h4>Add a New Player</h4>
  <%= form_for [@game, Player.new], remote: true do |f| %>
    <%= f.label :name, "Name:" %>
    <%= f.text_field :name %>
    <%= f.submit "Add a Player" %>
  <% end %>
</div>

<%= link_to("Return home!", games_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zebra Bowl</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'http://bootswatch.com/darkly/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container-fluid'>
      <div id='side-image' class='col-md-3'></div>
      <div class='col-md-3'></div>
      <div class='col-md-9'>
        <h1>Zebra Bowl!</h1>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/players/_new_player.html.erb
<div class="row" data-id="<%= locals[:id] %>">
  <div class="frame col">
    <%= params[:player][:name] %>
  </div>
  <% 10.times do %>
    <div class="frame col">
    </div>
  <% end %>
</div>

app/views/players/_new_player_form.html.erb
<%= form_tag(game_player_path(params[:game_id], locals[:id]), remote: true, method: "patch") do %>
  <%= label_tag(:score, "Bowl for #{params[:player][:name]}:") %>
  <%= text_field_tag(:score) %>
  <%= submit_tag("Bowl!") %>
<% end %>

app/views/players/_player_frames.html.erb
<div class="row" data-id="<%= locals[:player]["id"]%>">
  <div class="frame col">
    <%= locals[:player]["name"] %>
  </div>

  <% locals[:frames].each_with_index do |frame, index| %>
    <div class="frame col">
      <p>
        <% locals[:arrays][index].each do |move| %>
          <%= move %>
        <% end %>
      </p>
      <p><%= frame["cumulative_score"] %></p>
    </div>
  <% end %>

  <% (10 - locals[:frames].length).times do %>
    <div class="frame col">
    </div>
  <% end %>
</div>

app/views/players/create.js.erb
<% html = escape_javascript(render 'new_player', locals: {id: id}) %>
$('#bowlers-list').append("<%= html %>");

<% form = escape_javascript(render 'new_player_form', locals: {id: id}) %>
$('#bowlers-forms').append("<%= form %>");

$('#player_name').val('');

app/views/players/update.js.erb
<% player = JSON.parse(player) %>
<% frames = JSON.parse(frames) %>
<% arrays = JSON.parse(arrays) %>
<% html = escape_javascript(render 'player_frames', locals: {player: player, frames: frames, arrays: arrays}) %>

$('#bowlers-list .row[data-id=<%= player["id"] %>]').replaceWith("<%= html %>");
$('#bowlers-forms input[type=text]').val("");